enable_modelarts: 0

# eval datasets
interpolation: 'BILINEAR'
eval_path: '/path/to/mixed_rand/val'
eval_image_size: 224
eval_batch_size: 256
eval_interval: 1
eval_offset: -1
eval_num_workers: 4

# load model
pretrained: "/path/to/best_lam_ft/best.ckpt"

# network
backbone: 'vit_base_patch32'
class_num: 9
vit_config_path: 'src.vit.VitConfig'

open_profiler: 0
